# These are supported funding model platforms

github: awatson1978   
patreon: # Replace with a single Patreon username  
open_collective: abigail-watson  
ko_fi: # Replace with a single Ko-fi username  
tidelift: symptomatic/node-on-fhir  
community_bridge: node-on-fhir  
liberapay: #awatson1978
issuehunt: #awatson1978
otechie: #awatson1978
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
