# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml' version: 2.1 
# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects. 
# See: https://circleci.com/docs/2.0/orb-intro/ 

version: 2.1

orbs: 
  browser-tools: circleci/browser-tools@1.4.6
jobs: 
  testrunner: 
    docker: 
      - image: cimg/node:21.6.0-browsers
    steps: 
      - browser-tools/install-browser-tools
      - checkout

      - run:  node --version
      - run:  java --version
      - run:  google-chrome --version

      # npm install
      # npm run build
      # npm run test  

      # - run: 
      #   command: npm run test

      # - store_artifacts:
      #   path: ./test-reports

workflows: 
  version: 2
  e2e_test: 
    jobs: 
      - testrunner