# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml' version: 2.1 
# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects. 
# See: https://circleci.com/docs/2.0/orb-intro/ 

version: 2.1

orbs: 
  browser-tools: circleci/browser-tools@1.4.6
jobs: 
  testrunner: 
    docker: 
      - image: cimg/node:21.6.0-browsers
        name: node-on-fhir
        # cmd: ["/bin/bash"]
        environment:
          CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
          CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
          TZ: "/usr/share/zoneinfo/America/Chicago"
          CIRCLE_ENV: test
          NODE_ENV: test
          NIGHTWATCH: true
          DEBUG: true
          CXX: g++-4.8
          DISPLAY: :99.0
          NPM_PREFIX: /home/ubuntu/nvm/v0.10.33
          MONGO_URL: mongodb://mongo:27017/meteor
          NODE_OPTIONS: --max_old_space_size=3072
          TOOL_NODE_FLAGS: --max_old_space_size=3072        
          LANG: C.UTF-8
          LANGUAGE: C.UTF-8
          LC_ALL: C.UTF-8
          LC_NUMERIC: en_US.UTF-8
          TEST_BROWSER_DRIVER: chrome
      - image: mongo:3.6.8
        name: mongo

    steps: 
      - browser-tools/install-browser-tools
      - checkout

      - run:  node --version
      - run:  java --version
      - run:  google-chrome --version

      # Prepare for artifact and test results  collection equivalent to how it was done on 1.0.
      # In many cases you can simplify this from what is generated here.
      # 'See docs on artifact collection here https://circleci.com/docs/2.0/artifacts/'
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      # install locale for mongodb?
      - run: echo $LC_ALL

      # Install  Meteor
      - run: mkdir -p .meteor
      
      # If Meteor is already cached, do not need to build it again.
      # - run: if [ ! -e .meteor/meteor ]; then curl https://install.meteor.com?=release=1.11.0 | /bin/sh; else echo "Meteor seems to be cached"; fi;
      - run: curl https://install.meteor.com?=release=2.5.1 --insecure | sh
      # - run: npm install meteor

      # Link the meteor executable into /usr/bin
      - run: sudo ln -s .meteor/meteor /usr/bin/meteor

      # Lets see if we can get some config info 
      - run: pwd
      - run: ls -la


      # Lets see if we can get some config info 
      - run: cat .meteor/nightwatch.circle.json
      - run: cat .meteor/packages
      - run: cat .meteor/versions
      - run: meteor --version


      # npm install
      # npm run build
      # npm run test  

      # - run: 
      #   command: npm run test

      # - store_artifacts:
      #   path: ./test-reports

workflows: 
  version: 2
  e2e_test: 
    jobs: 
      - testrunner